### ISSUE TITLE
sh to shell plugin does not work.

### ISSUE THREAD

**Issue by willdoescode** [hackclub/markdown#12]
<img width="1215" alt="Screen Shot 2021-11-23 at 09 15 25" src="https://user-images.githubusercontent.com/53620720/143072171-c41c668f-3268-4d10-966c-4beda3d80bd3.png">
<img width="1190" alt="Screen Shot 2021-11-23 at 09 15 34" src="https://user-images.githubusercontent.com/53620720/143072200-4f78d16b-a388-4513-ba48-325b526beaa4.png">

**Comment by bashbaugh** [comment]
Should be fixed when redeployed after v0.0.42 is published

**Comment by bashbaugh** [comment]
This can be closed.
