### ISSUE TITLE
Client support

### ISSUE THREAD

**Issue by edvilme** [hackclub/markdown#4]
Hello, I was wondering if there are any plans for integrating client support (if it is of anny need, I would gladly contribute) or if there are other client alternatives you can recommend. 

I tried integrating it in the client side with 
`https://unpkg.com/@hackclub/markdown@0.0.1-alpha.0/dist/index.umd.js` and `https://cdn.jsdelivr.net/npm/@hackclub/markdown` without any luck. 

Either way,, thanks a lot.

**Comment by lachlanjc** [comment]
@edvilme Hey! So no, I have not tried that. The reason I didn’t publish a version like that is this library is designed to be used server-side—I didn’t pay attention to bundle size/optimization & it has quite a few dependencies. What are you trying to do client-side?

**Comment by edvilme** [comment]
I colead @Ctrl-Alt-Tec HackClub and we are trying to create our blog/workshop platform using Markdown in github as a way to store our content.

We became interested in this library as we want the output to be similar to workshops.hackclub.com and became particularly interested in the syntax highlighting.

We were able to integrate highlight.js with showdown and achieve pretty good results. Here is our (wip) page https://ctrl-alt-tec.gihub.io/Watermelon/beta

Either way, I leave this issue open for anyone that may just as well be looking for client support.

**Comment by lachlanjc** [comment]
Got it. If you want to use Next.js, this is how the main site works: https://github.com/hackclub/workshops/blob/master/pages/%5Bslug%5D.js#L39

Would also work with Express, etc.

**Comment by edvilme** [comment]
Thnks a lot! :D 
We will finish this project soon and can't wait to share with the world
